version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql_server_container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: M1croshitSqlServer
    ports:
      - "1433:1433"
    networks:
      - app-network

  # app:
  #   build:
  #     context: ./Backend 
  #     dockerfile: Dockerfile
  #   container_name: crashapp
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
